default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: root
  socket: /var/lib/mysql/mysql.sock

development:
  <<: *default
  database: git-rpg_development

test:
  <<: *default
  database: git-rpg_test

production:
  <<: *default
  database: git-rpg
  url: <%= ENV['DATABASE_URL'] %>
  username: root
  password: <%= ENV['MYSQL_PASSWORD'] %>
